---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: media-critical
value: 1000000
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "High priority for media workloads like Plex to preempt lower-priority pods."
