apiVersion: v1
kind: Secret
metadata:
    name: couchdb-secret
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:VmACSwc=,iv:wUZZmMzyJMbDANSsCXTfnrSUrvWOf6WK1kz8TEqxx/Y=,tag:YRj7fV9eWwYvu0WTb7QthA==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:68f2Sbs3NbZtdErDgQEIt3ZRGdCpUgXXcpO5CEQmolc=,iv:bJL6Zo8AIG4y4oMf5CICGnZiizTlxPjk2dw8IYGcNvA=,tag:zdtOs776RcQky+qqdNAW8g==,type:str]
sops:
    age:
        - recipient: age1meu65v2nuw6ntzn8fghgc59mmkcm2uhynj4ydchrpdp6audq2y6q85kadn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSb2pSQ0VHZnUzTzlBeWVC
            WSthTjF2LzhhRlhRcHgzTU9XekEwOXd0SnhNCjVCbkxLYjVKN0lqYkNEbUF5aFhy
            QkhLdlF0b3hBamJySW9HbURVZlUrVmsKLS0tIDFzT0F5dWVUSE02Y29yUW44VEpn
            SjRTUnRkMWJXc2VLSEF2clZud0lBMVEKchiEUuGVCYMEIQKunTK/0OiVUVLB9XDt
            /4A0H0gPO1PJiWgBrotSooHCz6DThLKJu3ZpzO6j/oVbnwNs7G5n0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T22:01:22Z"
    mac: ENC[AES256_GCM,data:UHqN9+SFRsriMGWhzoX1Z7k0gYEYP4UroD+VBuumKkgXMbQr4kP0QOfI9YNx6is9u++GbWBHZUsk/eiNIZkbFnSKx5ejEhLhFzNxqR3+OO83i+E0WzUBUItKjmUpSRnEKZ3AmbyNhfXAoGCDPhMtao2ef8rAD2mbwSeD6wBHHaU=,iv:E0mh5LX7b9XsvujMvByiJMFMicy0CB78EbkFdkYdkAk=,tag:yPzL/gR+wTnk6UoGJgmqJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
